channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black=23.3.0
  - flake8=6.0.0
  - ipython=8.12.0
  - isort=5.12.0
  - pep8-naming=0.13.3
  - pip=23.1.1
  - pre-commit=3.2.2
  - pre-commit-hooks=4.4.0
  - pydocstyle=6.3.0
  - pytest-cov=4.0.0
  - pytest=7.3.1
  - numpy=1.22.3
  - pandas=2.0.3
  - python=3.10.10
  - pytorch::pytorch=2.0.0
  - pip:
    - sphinx-multiversion==0.2.4
    - aiofiles==23.1.0
    - pydantic==1.9.0
    - evaluate==0.4.0
    - scikit-learn==1.3.0
    - rouge-score==0.1.2
    - aiolimiter==1.1.0
    - backoff==2.2.1
    - openai==1.3.4
    - datasets==2.14.6
    - mlflow==2.8.1
    - hydra-core==1.3.2
    - tiktoken==0.3.1
    - transformers==4.34.0
    - sentencepiece==0.1.99
    - python-dotenv==1.0.0
    - openpyxl==3.1.2
    # NOTE: This is needed to use `device_map` with the transformers library. So it could be skipped.
    - accelerate==0.25.0
    # NOTE: This is needed to flash attention. So it could be skipped.
    # - flash-attn==2.3.1.post1
